version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.6
  github: haskell-works/github-release@1.3.0
  hackage: haskell-works/hackage@1.1.0

executors:
  darwin:
    macos:
      xcode: 10.0
  ghc-8_6_5_old:
    docker:
      - image: quay.io/haskell_works/ghc-8.6.5:ubuntu-16.04
  ghc-8_8_3_old:
    docker:
      - image: quay.io/haskell_works/ghc-8.8.3:ubuntu-16.04

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          binary-cache-uri-suffix: -ubuntu-16.04
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          binary-cache-uri-suffix: -ubuntu-16.04
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct

      - haskell/build-with-binary-cache:
          name: GHC 8.8.3
          executor: haskell/ghc-8_8_3
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          binary-cache-uri-suffix: -ubuntu-16.04
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct
          workspace-dir: workspace/ghc-8.8.3
          write-result-workspace: true

      - haskell/build-with-binary-cache:
          name: i386 GHC 8.8.3
          executor: haskell/i386-ghc-8_8_3
          context: haskell-ci
          cabal-cache-uri: https://github.com/haskell-works/cabal-cache/releases/download/v1.0.1.7/i386-cabal-cache_x86_64_linux.tar.gz
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct
          workspace-dir: workspace/i386-ghc-8.8.3
          write-result-workspace: true

      - github/release-cabal:
          context: haskell-ci
          name: GitHub Release
          attach-workspace: true
          requires:
            - GHC 8.4.4
            - GHC 8.6.5
            - GHC 8.8.3
            - i386 GHC 8.8.3
          checkout: true
          filters:
            branches:
              only: master

      # - hackage/upload:
      #     context: haskell-ci
      #     publish: true
      #     requires:
      #       - GitHub Release
