name: ci
on:
  pull_request: {}

jobs:

  emulated-i386:
    runs-on: ubuntu-latest
    container:
      image: i386/debian:bullseye
    steps:
    - name: install
      run: |
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y ghc cabal-install libghc-quickcheck2-dev libghc-tasty-dev libghc-tasty-quickcheck-dev git make curl libghc-exceptions-dev
      shell: bash
    - uses: actions/checkout@v1
    - name: build
      run: |
         ghc --version
         cabal --version
         cabal update
         cabal configure --enable-tests --constraint="quickcheck-classes -aeson -semigroupoids -vector"
         cabal build
         cabal haddock
         cabal sdist
    - name: test
      run: |
         LC_ALL=C.UTF-8 cabal test --test-show-details=streaming -j1
